CREATE TABLE "public"."opportunities" (
  "estado"              text,
  "fecha"               text,
  "postal_id"           bigint,
  "tasacion"            text,
  "domicilio"           text,
  "propietario"         text,
  "telefono"            text,
  "en_venta"            text,
  "memo"                character varying,
  "id"                  bigint                      GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME "public"."opportunities_id_seq1") NOT NULL,
  "source_id"           bigint,
  "comercial_user_id"   bigint,
  "domain_id"           bigint,
  "created_at"          timestamp without time zone DEFAULT now(),
  "fase_id"             bigint,
  "deleted_at"          timestamp without time zone,
  "is_favorite"         boolean                     NOT NULL DEFAULT false,
  CONSTRAINT "opportunities_id_key" UNIQUE (id),
  CONSTRAINT "opportunities_pkey" PRIMARY KEY (id),
  CONSTRAINT "opportunities_domain_id_fkey" FOREIGN KEY (domain_id) REFERENCES public.domain(id),
  CONSTRAINT "opportunities_postal_id_fkey" FOREIGN KEY (postal_id) REFERENCES public.postal(id),
  CONSTRAINT "opportunities_comercial_user_id_fkey" FOREIGN KEY (comercial_user_id) REFERENCES public.profiles(id),
  CONSTRAINT "opportunities_source_id_fkey" FOREIGN KEY (source_id) REFERENCES public.sources(id),
  CONSTRAINT "opportunities_fase_id_fkey" FOREIGN KEY (fase_id) REFERENCES public.phases(id)
);

ALTER TABLE "public"."opportunities"
  ENABLE ROW LEVEL SECURITY;

CREATE INDEX idx_opportunities_comercial_user_id ON public.opportunities USING btree (comercial_user_id)
  WHERE (deleted_at IS NULL);

CREATE INDEX idx_opportunities_source_id ON public.opportunities USING btree (source_id)
  WHERE (deleted_at IS NULL);

CREATE POLICY "opportunities_insert_by_role" ON "public"."opportunities"
  FOR INSERT
  TO "authenticated"
  WITH CHECK (
    public.crm_current_role() = ANY (ARRAY['admin'::text, 'coordinador'::text])
    OR (
      public.crm_current_role() = 'comercial'::text
      AND NOT public.crm_can_manage_visits()
      AND comercial_user_id = public.crm_current_profile_id()
    )
  );

CREATE POLICY "opportunities_select_by_role" ON "public"."opportunities"
  FOR SELECT
  TO "authenticated"
  USING (public.crm_can_read_opportunity(id));

CREATE POLICY "opportunities_update_by_role" ON "public"."opportunities"
  FOR UPDATE
  TO "authenticated"
  USING (public.crm_can_write_opportunity(id))
  WITH CHECK (public.crm_can_write_opportunity(id));

GRANT INSERT, SELECT, UPDATE ON TABLE "public"."opportunities" TO "appsheet_user";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."opportunities" TO "postgres", "service_role";

COMMENT ON TABLE "public"."opportunities" IS 'Oportunidades';

REVOKE ALL ON TABLE "public"."opportunities" FROM "authenticated";

GRANT INSERT, SELECT, UPDATE ON TABLE "public"."opportunities" TO "authenticated";
